<html>
    <head>
        <title>API Documentation</title>
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="../css/api-doc.css">
    </head>
    <body>
        <div class="api-doc">

            <h1><?= $item->collection->name; ?></h1>

            <h2><span class="method <?= strtolower($item->method); ?>"><?= $item->method; ?></span> <?= $item->name; ?></h2>
            <p class="url"><?= $item->url; ?></p>
            <p class="description"><?= $item->description; ?></p>

            <h3>HEADERS</h3>
            <dl class="headers">
            <?php foreach($item->headers as $header): ?>
                <dt><?= $header->key; ?></dt>
                <dd><?= $header->value; ?></dd>
            <?php endforeach; ?>
            </dl>

            <h3>BODY</h3>
            <pre class="body"><?= $item->body; ?></pre>

        <div>
    </body>
</html>